language: python

cache: pip

python:
  - 2.7
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
  - pipenv run pip install -r requirements.txt
  - pipenv run update_rir

script:
  pipenv run pytest --cov=iptocc --cov-report=xml -v

after_success:
  pipenv run codecov

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"