environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - "%PYTHON%\\Scripts\\pip.exe install pipenv"
  - "%PYTHON%\\Scripts\\pipenv.exe install --dev --skip-lock"
  - "%PYTHON%\\Scripts\\pipenv.exe run pip install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pipenv.exe run update_rir"

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - "%PYTHON%\\Scripts\\pipenv.exe run pytest --cov=iptocc --cov-report=xml -v"

on_success:
  - "%PYTHON%\\Scripts\\pipenv.exe run codecov -f coverage.xml"
